import argparse
import datetime as dt
import fnmatch
import json
import subprocess
import sys
import uuid
from pathlib import Path
from typing import Any

from validate_control_plane_json import run_validation


NO_CLAIM_ALLOWED = "NO_CLAIM_ALLOWED"
OPERATOR_AGENT_ID = "operator"
DEFAULT_RUN_OUTPUT_DIR = Path("lab/agent_runs/operator_latest")

POLICY_PATHS = {
    "tool_permission_matrix": Path("lab/agent_policy/tool_permission_matrix.json"),
    "forbidden_surfaces": Path("lab/agent_policy/forbidden_surfaces.json"),
    "strike_rules": Path("lab/agent_policy/strike_rules.json"),
    "freeze_rules": Path("lab/agent_policy/freeze_rules.json"),
    "autonomy_levels": Path("lab/agent_policy/autonomy_levels.json"),
}

SCHEMA_PATHS = {
    "task_packet_schema": Path("schemas/task_packet.schema.json"),
    "agent_profile_schema": Path("schemas/agent_profile.schema.json"),
    "agent_scorecard_schema": Path("schemas/agent_scorecard.schema.json"),
    "audit_event_schema": Path("schemas/audit_event.schema.json"),
    "reward_log_schema": Path("schemas/reward_log.schema.json"),
    "block_manifest_schema": Path("schemas/block_manifest.schema.json"),
}

CONTROL_PLANE_JSON_GLOBS = (
    "lab/agent_tasks/*.json",
    "lab/agent_registry/*.agent.json",
    "lab/agent_tasks/fixtures/**/*.json",
)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Local control-plane PR operator (mechanical only, deny-by-default).")
    parser.add_argument(
        "--mode",
        required=True,
        choices=["inspect", "validate-staged", "prepare-draft-pr"],
        help="Execution mode.",
    )
    parser.add_argument("--task-packet", required=True, help="Path to JSON task packet.")
    parser.add_argument("--pretty", action="store_true", help="Pretty-print JSON output.")
    parser.add_argument("--output-dir", default=str(DEFAULT_RUN_OUTPUT_DIR), help="Output dir for validate artifacts.")
    parser.add_argument("--execute-pr-actions", action="store_true", help="Actually run commit/push/draft PR creation.")
    parser.add_argument("--commit-message", help="Commit message used in --mode prepare-draft-pr.")
    parser.add_argument("--pr-title", help="Draft PR title used in --mode prepare-draft-pr.")
    parser.add_argument("--pr-body", default="Mechanical control-plane draft PR generated by agent_pr_operator.", help="Draft PR body.")
    parser.add_argument("--base-branch", default="main", help="Base branch for draft PR creation.")
    parser.add_argument("--merge", action="store_true", help="Forbidden action (always denied).")
    parser.add_argument("--ready-pr", action="store_true", help="Forbidden action (always denied).")
    parser.add_argument("--edit-branch-protection", action="store_true", help="Forbidden action (always denied).")
    return parser.parse_args(argv)


def run_command(command: list[str]) -> dict[str, Any]:
    completed = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    return {
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def python_executable() -> str:
    executable = sys.executable.strip() if isinstance(sys.executable, str) else ""
    return executable or "python"


def normalize_path(path: str) -> str:
    normalized = path.strip().replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized


def load_json(path: Path) -> tuple[Any | None, str | None]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None, f"MISSING_JSON_FILE: {normalize_path(str(path))}"
    except json.JSONDecodeError as exc:
        return None, f"INVALID_JSON: {normalize_path(str(path))}: {exc}"
    except OSError as exc:
        return None, f"JSON_READ_FAILED: {normalize_path(str(path))}: {exc}"
    return payload, None


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def current_branch() -> tuple[str, str | None]:
    result = run_command(["git", "branch", "--show-current"])
    if result["returncode"] != 0:
        message = str(result["stderr"]).strip() or "unknown error"
        return "", f"GIT_BRANCH_QUERY_FAILED: {message}"
    return str(result["stdout"]).strip(), None


def git_status_porcelain() -> tuple[list[str], str | None]:
    result = run_command(["git", "status", "--porcelain"])
    if result["returncode"] != 0:
        message = str(result["stderr"]).strip() or "unknown error"
        return [], f"GIT_STATUS_FAILED: {message}"
    return [line.rstrip("\n") for line in str(result["stdout"]).splitlines() if line.strip()], None


def staged_files() -> tuple[list[str], str | None]:
    result = run_command(["git", "diff", "--cached", "--name-only"])
    if result["returncode"] != 0:
        message = str(result["stderr"]).strip() or "unknown error"
        return [], f"GIT_STAGED_DIFF_FAILED: {message}"
    files = [normalize_path(line) for line in str(result["stdout"]).splitlines() if line.strip()]
    return sorted(set(files)), None


def matches_pattern(path: str, pattern: str) -> bool:
    candidate = normalize_path(path)
    rule = normalize_path(pattern)
    if not rule:
        return False
    if fnmatch.fnmatchcase(candidate, rule):
        return True
    if rule.endswith("/"):
        return candidate.startswith(rule)
    return candidate == rule


def path_hits_any(path: str, patterns: list[str]) -> bool:
    return any(matches_pattern(path, pattern) for pattern in patterns)


def parse_task_packet(packet: Any) -> tuple[dict[str, Any], list[str]]:
    errors: list[str] = []
    if not isinstance(packet, dict):
        return {}, ["TASK_PACKET_NOT_OBJECT"]

    required = ["task_id", "agent_id", "allowed_files", "forbidden_files", "required_checks", "authorization"]
    for key in required:
        if key not in packet:
            errors.append(f"TASK_PACKET_MISSING_FIELD: {key}")

    allowed_files = packet.get("allowed_files")
    forbidden_files = packet.get("forbidden_files")
    required_checks = packet.get("required_checks")
    if not isinstance(allowed_files, list) or not allowed_files or not all(isinstance(x, str) and x.strip() for x in allowed_files):
        errors.append("TASK_PACKET_INVALID_ALLOWED_FILES")
    if not isinstance(forbidden_files, list) or not forbidden_files or not all(isinstance(x, str) and x.strip() for x in forbidden_files):
        errors.append("TASK_PACKET_INVALID_FORBIDDEN_FILES")
    if not isinstance(required_checks, list) or not required_checks or not all(isinstance(x, str) and x.strip() for x in required_checks):
        errors.append("TASK_PACKET_INVALID_REQUIRED_CHECKS")
    return packet, errors


def is_explicit_true(value: Any) -> bool:
    return isinstance(value, bool) and value is True


def read_authorization_flags(packet: dict[str, Any]) -> dict[str, bool]:
    authorization = packet.get("authorization")
    authz_payload = authorization if isinstance(authorization, dict) else {}
    return {
        "authorization_present": isinstance(authorization, dict),
        "human_authorized": is_explicit_true(authz_payload.get("human_authorized", False)),
        "allow_commit": is_explicit_true(authz_payload.get("allow_commit", packet.get("authorize_commit", False))),
        "allow_push": is_explicit_true(authz_payload.get("allow_push", packet.get("authorize_push", False))),
        "allow_create_pr": is_explicit_true(
            authz_payload.get("allow_create_pr", packet.get("authorize_create_pr", False))
        ),
        "allow_ready": is_explicit_true(authz_payload.get("allow_ready", packet.get("authorize_ready_pr", False))),
        "allow_merge": is_explicit_true(authz_payload.get("allow_merge", packet.get("authorize_merge_pr", False))),
    }


def collect_prepare_authorization_blockers(packet: dict[str, Any], authz_flags: dict[str, bool]) -> list[str]:
    blockers: list[str] = []
    authorization = packet.get("authorization")
    if not isinstance(authorization, dict):
        return ["missing_authorization"]

    required_fields = [
        "human_authorized",
        "allow_commit",
        "allow_push",
        "allow_create_pr",
        "allow_ready",
        "allow_merge",
    ]
    missing_fields = [field for field in required_fields if field not in authorization]
    if missing_fields:
        blockers.append("missing_authorization")

    if not authz_flags["allow_commit"]:
        blockers.append("commit_not_authorized")
    if not authz_flags["allow_push"]:
        blockers.append("push_not_authorized")
    if not authz_flags["allow_create_pr"]:
        blockers.append("create_pr_not_authorized")
    if not authz_flags["human_authorized"]:
        blockers.append("human_review_required")

    return sorted(set(blockers))


def parse_forbidden_surfaces(policy: Any) -> tuple[dict[str, list[str]], list[str]]:
    if not isinstance(policy, dict):
        return {"absolute_forbidden_paths": [], "restricted_human_review_paths": []}, ["FORBIDDEN_SURFACES_NOT_OBJECT"]
    raw_absolute = policy.get("absolute_forbidden_paths")
    raw_restricted = policy.get("restricted_human_review_paths")
    errors: list[str] = []
    if not isinstance(raw_absolute, list) or not all(isinstance(x, str) and x.strip() for x in raw_absolute):
        errors.append("FORBIDDEN_SURFACES_INVALID_ABSOLUTE_FORBIDDEN_PATHS")
    if not isinstance(raw_restricted, list) or not all(isinstance(x, str) and x.strip() for x in raw_restricted):
        errors.append("FORBIDDEN_SURFACES_INVALID_RESTRICTED_HUMAN_REVIEW_PATHS")
    if errors:
        return {"absolute_forbidden_paths": [], "restricted_human_review_paths": []}, errors
    return {
        "absolute_forbidden_paths": [normalize_path(item) for item in raw_absolute],
        "restricted_human_review_paths": [normalize_path(item) for item in raw_restricted],
    }, []


def parse_tool_matrix(policy: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(policy, dict):
        return ["TOOL_PERMISSION_MATRIX_NOT_OBJECT"]
    if policy.get("deny_by_default") is not True:
        errors.append("DENY_BY_DEFAULT_NOT_ENFORCED")
    if str(policy.get("default_effect", "")).upper() != "DENY":
        errors.append("DEFAULT_EFFECT_IS_NOT_DENY")
    return errors


def critical_freeze_by_policy(forbidden_hits: list[str], forbidden_policy: Any, freeze_policy: Any) -> bool:
    if forbidden_hits:
        return True
    if isinstance(forbidden_policy, dict) and forbidden_policy.get("critical_violation_freeze_immediate") is True:
        return False
    if isinstance(freeze_policy, dict):
        freeze_list = freeze_policy.get("freeze_immediately_on")
        if isinstance(freeze_list, list):
            return False
    return False


def validate_staged_scope(
    staged: list[str],
    allowed_files: list[str],
    task_forbidden_files: list[str],
    policy_absolute_forbidden_paths: list[str],
    policy_restricted_human_review_paths: list[str],
    packet: dict[str, Any],
    authz_flags: dict[str, bool],
) -> tuple[list[str], list[str]]:
    violations: list[str] = []
    forbidden_hits: list[str] = []
    control_plane_exception = is_explicit_true(packet.get("control_plane_exception", False))
    human_review_required = packet.get("human_review_required") is True
    exception_reason = str(packet.get("exception_reason", "")).strip()
    allow_restricted_human_review = (
        control_plane_exception
        and human_review_required
        and bool(exception_reason)
        and (authz_flags["allow_ready"] is False)
        and (authz_flags["allow_merge"] is False)
    )
    for path in staged:
        in_allowed_files = path_hits_any(path, allowed_files)
        if not in_allowed_files:
            violations.append(f"STAGED_OUTSIDE_ALLOWED_FILES: {path}")
        if path_hits_any(path, task_forbidden_files):
            forbidden_hits.append(f"TASK_FORBIDDEN_FILE_HIT: {path}")
        if path_hits_any(path, policy_absolute_forbidden_paths):
            forbidden_hits.append(f"POLICY_ABSOLUTE_FORBIDDEN_SURFACE_HIT: {path}")
        if path_hits_any(path, policy_restricted_human_review_paths):
            restricted_allowed = allow_restricted_human_review and in_allowed_files
            if not restricted_allowed:
                forbidden_hits.append(f"POLICY_RESTRICTED_HUMAN_REVIEW_SURFACE_HIT: {path}")
    return sorted(set(violations)), sorted(set(forbidden_hits))


def parse_staged_json_files(staged: list[str]) -> list[str]:
    errors: list[str] = []
    for path in staged:
        if not path.lower().endswith(".json"):
            continue
        file_path = Path(path)
        payload, err = load_json(file_path)
        if err:
            errors.append(err)
            continue
        if payload is None:
            errors.append(f"JSON_PARSE_EMPTY: {path}")
    return sorted(set(errors))


def matches_any_glob(path: str, patterns: tuple[str, ...]) -> bool:
    normalized = normalize_path(path)
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in patterns)


def strict_schema_validation_paths(task_packet_path: Path, staged: list[str]) -> list[str]:
    paths: list[str] = [normalize_path(str(task_packet_path))]
    for path in staged:
        if not path.lower().endswith(".json"):
            continue
        if matches_any_glob(path, CONTROL_PLANE_JSON_GLOBS):
            paths.append(normalize_path(path))
    return sorted(set(paths))


def summarize_command(result: dict[str, Any]) -> dict[str, Any]:
    stdout = str(result.get("stdout", ""))
    stderr = str(result.get("stderr", ""))
    return {
        "command": result.get("command", []),
        "returncode": int(result.get("returncode", 1)),
        "stdout_tail": stdout[-4000:],
        "stderr_tail": stderr[-4000:],
    }


def run_required_local_checks() -> list[dict[str, Any]]:
    python_cmd = python_executable()
    commands = [
        [python_cmd, "scripts/check_workspace_hygiene.py", "--pretty"],
        [python_cmd, "scripts/report_local_agent_session.py", "--pretty"],
    ]
    return [run_command(command) for command in commands]


def default_verdicts(success: bool) -> tuple[str, str, str]:
    if success:
        return ("CONTROL_PLANE_TOOLING_ONLY", "LOCAL_OPERATOR_HYGIENE_VALIDATION_ONLY", NO_CLAIM_ALLOWED)
    return ("BLOCKED", "BLOCKED", NO_CLAIM_ALLOWED)


def build_audit_event(
    *,
    run_id: str,
    mode: str,
    branch: str,
    task_id: str,
    agent_id: str,
    checked_files: list[str],
    forbidden_hits: list[str],
    required_checks: list[str],
    checks_passed: list[str],
    checks_failed: list[str],
    freeze_required: bool,
    success: bool,
) -> dict[str, Any]:
    software_verdict, evidence_verdict, claim_verdict = default_verdicts(success)
    return {
        "run_id": run_id,
        "timestamp": now_iso(),
        "mode": mode,
        "branch": branch,
        "task_id": task_id,
        "agent_id": agent_id,
        "checked_files": checked_files,
        "forbidden_hits": forbidden_hits,
        "required_checks": required_checks,
        "checks_passed": checks_passed,
        "checks_failed": checks_failed,
        "freeze_required": freeze_required,
        "software_verdict": software_verdict,
        "evidence_verdict": evidence_verdict,
        "claim_verdict": claim_verdict,
    }


def build_reward_log(
    *,
    run_id: str,
    task_id: str,
    agent_id: str,
    checks_passed: list[str],
    checks_failed: list[str],
    strikes: int,
    freeze_required: bool,
) -> dict[str, Any]:
    positive_points = len(checks_passed) * 5
    negative_points = len(checks_failed) * 7 + strikes * 3
    autonomy_delta = "DECREASE" if freeze_required else "NONE"
    final_score = max(-100, min(100, positive_points - negative_points))
    return {
        "run_id": run_id,
        "task_id": task_id,
        "agent_id": agent_id,
        "positive_points": positive_points,
        "negative_points": negative_points,
        "strikes": strikes,
        "autonomy_delta": autonomy_delta,
        "final_score": final_score,
        "reviewed_by_human": False,
        "claim_verdict": NO_CLAIM_ALLOWED,
    }


def write_non_canonical_outputs(output_dir: Path, audit_event: dict[str, Any], reward_log: dict[str, Any]) -> list[str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    audit_path = output_dir / "audit_event.json"
    reward_path = output_dir / "reward_log.json"
    audit_path.write_text(json.dumps(audit_event, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    reward_path.write_text(json.dumps(reward_log, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    written.append(normalize_path(str(audit_path)))
    written.append(normalize_path(str(reward_path)))
    return written


def command_failed(result: dict[str, Any]) -> bool:
    return int(result.get("returncode", 1)) != 0


def perform_shared_loads(task_packet_path: Path) -> tuple[dict[str, Any], list[str], dict[str, Any]]:
    errors: list[str] = []
    loaded: dict[str, Any] = {}
    task_packet_payload, task_err = load_json(task_packet_path)
    if task_err:
        errors.append(task_err)
    loaded["task_packet"] = task_packet_payload

    for key, path in POLICY_PATHS.items():
        payload, err = load_json(path)
        loaded[key] = payload
        if err:
            errors.append(err)
    for key, path in SCHEMA_PATHS.items():
        payload, err = load_json(path)
        loaded[key] = payload
        if err:
            errors.append(err)

    parsed_packet, packet_errors = parse_task_packet(task_packet_payload)
    errors.extend(packet_errors)
    errors.extend(parse_tool_matrix(loaded.get("tool_permission_matrix")))
    forbidden_surface_paths, forbidden_parse_errors = parse_forbidden_surfaces(loaded.get("forbidden_surfaces"))
    errors.extend(forbidden_parse_errors)

    context = {
        "task_packet": parsed_packet,
        "policy_absolute_forbidden_paths": forbidden_surface_paths.get("absolute_forbidden_paths", []),
        "policy_restricted_human_review_paths": forbidden_surface_paths.get("restricted_human_review_paths", []),
    }
    return loaded, sorted(set(errors)), context


def deny_forbidden_cli_actions(args: argparse.Namespace, task_packet: dict[str, Any]) -> list[str]:
    violations: list[str] = []
    authz = read_authorization_flags(task_packet)
    if args.merge:
        violations.append("MERGE_REQUEST_DENIED")
    if args.ready_pr:
        violations.append("READY_PR_REQUEST_DENIED")
    if args.edit_branch_protection:
        violations.append("BRANCH_PROTECTION_EDIT_DENIED")
    # Local operator never allows these autonomous actions in this phase.
    if authz["allow_ready"]:
        violations.append("TASK_PACKET_AUTHORIZE_READY_PR_TRUE_DENIED")
    if authz["allow_merge"]:
        violations.append("TASK_PACKET_AUTHORIZE_MERGE_PR_TRUE_DENIED")
    if bool(task_packet.get("request_merge", False)):
        violations.append("TASK_PACKET_MERGE_REQUEST_DENIED")
    if bool(task_packet.get("request_ready_pr", False)):
        violations.append("TASK_PACKET_READY_PR_REQUEST_DENIED")
    if bool(task_packet.get("request_branch_protection_edit", False)):
        violations.append("TASK_PACKET_BRANCH_PROTECTION_EDIT_DENIED")
    return violations


def execute_prepare_actions(args: argparse.Namespace, branch: str) -> tuple[list[dict[str, Any]], str]:
    command_results: list[dict[str, Any]] = []

    commit_message = (args.commit_message or "").strip()
    pr_title = (args.pr_title or "").strip()
    if not commit_message:
        raise RuntimeError("MISSING_COMMIT_MESSAGE_FOR_PREPARE_DRAFT_PR")
    if not pr_title:
        raise RuntimeError("MISSING_PR_TITLE_FOR_PREPARE_DRAFT_PR")

    commit_result = run_command(["git", "commit", "-m", commit_message])
    command_results.append(summarize_command(commit_result))
    if command_failed(commit_result):
        raise RuntimeError("GIT_COMMIT_FAILED")

    push_result = run_command(["git", "push", "-u", "origin", branch])
    command_results.append(summarize_command(push_result))
    if command_failed(push_result):
        raise RuntimeError("GIT_PUSH_FAILED")

    pr_create_command = [
        "gh",
        "pr",
        "create",
        "--draft",
        "--base",
        args.base_branch,
        "--head",
        branch,
        "--title",
        pr_title,
        "--body",
        args.pr_body,
    ]
    pr_result = run_command(pr_create_command)
    command_results.append(summarize_command(pr_result))
    if command_failed(pr_result):
        raise RuntimeError("GH_PR_CREATE_FAILED")

    pr_url = str(pr_result.get("stdout", "")).strip().splitlines()[-1].strip()
    if not pr_url:
        raise RuntimeError("DRAFT_PR_URL_NOT_FOUND")
    return command_results, pr_url


def render(payload: dict[str, Any], pretty: bool) -> None:
    print(json.dumps(payload, indent=2 if pretty else None, sort_keys=True))


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    task_packet_path = Path(args.task_packet)
    output_dir = Path(args.output_dir)
    run_id = f"operator-{dt.datetime.now(dt.timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid.uuid4().hex[:8]}"

    branch, branch_error = current_branch()
    status_lines, status_error = git_status_porcelain()
    loaded, load_errors, context = perform_shared_loads(task_packet_path)
    packet: dict[str, Any] = context.get("task_packet", {}) if isinstance(context.get("task_packet"), dict) else {}

    base_errors: list[str] = []
    if branch_error:
        base_errors.append(branch_error)
    if status_error:
        base_errors.append(status_error)
    base_errors.extend(load_errors)

    task_id = str(packet.get("task_id", "unknown_task"))
    agent_id = str(packet.get("agent_id", OPERATOR_AGENT_ID))
    required_checks = list(packet.get("required_checks", [])) if isinstance(packet.get("required_checks"), list) else []
    authz_flags = read_authorization_flags(packet)
    prepare_authz_blockers = collect_prepare_authorization_blockers(packet, authz_flags) if args.mode == "prepare-draft-pr" else []

    if args.mode == "inspect":
        output = {
            "run_id": run_id,
            "timestamp": now_iso(),
            "mode": "inspect",
            "branch": branch,
            "task_id": task_id,
            "agent_id": agent_id,
            "git_status_porcelain": status_lines,
            "json_parse_errors": sorted(set(base_errors)),
            "policies_loaded": sorted(POLICY_PATHS.keys()),
            "schemas_loaded": sorted(SCHEMA_PATHS.keys()),
            "software_verdict": "CONTROL_PLANE_TOOLING_ONLY" if not base_errors else "BLOCKED",
            "evidence_verdict": "SCHEMA_AND_METADATA_INSPECTION_ONLY" if not base_errors else "BLOCKED",
            "claim_verdict": NO_CLAIM_ALLOWED,
        }
        render(output, args.pretty)
        return 0 if not base_errors else 1

    staged, staged_error = staged_files()
    errors = list(base_errors)
    if staged_error:
        errors.append(staged_error)

    allowed_files = list(packet.get("allowed_files", [])) if isinstance(packet.get("allowed_files"), list) else []
    task_forbidden_files = list(packet.get("forbidden_files", [])) if isinstance(packet.get("forbidden_files"), list) else []
    policy_absolute_forbidden_paths = list(context.get("policy_absolute_forbidden_paths", []))
    policy_restricted_human_review_paths = list(context.get("policy_restricted_human_review_paths", []))

    staged_scope_violations, forbidden_hits = validate_staged_scope(
        staged=staged,
        allowed_files=allowed_files,
        task_forbidden_files=task_forbidden_files,
        policy_absolute_forbidden_paths=policy_absolute_forbidden_paths,
        policy_restricted_human_review_paths=policy_restricted_human_review_paths,
        packet=packet,
        authz_flags=authz_flags,
    )
    errors.extend(staged_scope_violations)
    errors.extend(forbidden_hits)
    json_staged_errors = parse_staged_json_files(staged)
    errors.extend(json_staged_errors)
    strict_schema_targets = strict_schema_validation_paths(task_packet_path, staged)
    strict_schema_result = run_validation(
        selected_paths=strict_schema_targets,
        include_fixtures=False,
    )
    if not strict_schema_result.get("ok", False):
        strict_errors = strict_schema_result.get("errors", [])
        if isinstance(strict_errors, list):
            for strict_error in strict_errors:
                errors.append(f"STRICT_SCHEMA_VALIDATION_FAILED: {strict_error}")
        else:
            errors.append("STRICT_SCHEMA_VALIDATION_FAILED: UNKNOWN_ERROR")

    denied_action_violations = deny_forbidden_cli_actions(args, packet)
    errors.extend(denied_action_violations)
    if prepare_authz_blockers:
        errors.extend([f"PREPARE_AUTHORIZATION_BLOCKED: {blocker}" for blocker in prepare_authz_blockers])

    check_results = run_required_local_checks()
    check_summaries = [summarize_command(result) for result in check_results]
    for result in check_summaries:
        if int(result["returncode"]) != 0:
            errors.append(f"REQUIRED_CHECK_FAILED: {' '.join(result['command'])}")

    checks_passed: list[str] = []
    checks_failed: list[str] = []
    if not staged_scope_violations:
        checks_passed.append("staged_scope_check")
    else:
        checks_failed.append("staged_scope_check")
    if not json_staged_errors:
        checks_passed.append("staged_json_parse")
    else:
        checks_failed.append("staged_json_parse")
    if strict_schema_result.get("ok", False):
        checks_passed.append("strict_schema_validation")
    else:
        checks_failed.append("strict_schema_validation")
    for summary in check_summaries:
        check_name = " ".join(summary["command"])
        if int(summary["returncode"]) == 0:
            checks_passed.append(check_name)
        else:
            checks_failed.append(check_name)

    critical_freeze = bool(forbidden_hits or denied_action_violations)
    if critical_freeze_by_policy(forbidden_hits, loaded.get("forbidden_surfaces"), loaded.get("freeze_rules")):
        critical_freeze = True

    unique_errors = sorted(set(errors))
    success = not unique_errors
    strikes = len(forbidden_hits) + len(denied_action_violations)

    audit_event = build_audit_event(
        run_id=run_id,
        mode=args.mode,
        branch=branch,
        task_id=task_id,
        agent_id=agent_id,
        checked_files=staged,
        forbidden_hits=forbidden_hits,
        required_checks=required_checks,
        checks_passed=sorted(set(checks_passed)),
        checks_failed=sorted(set(checks_failed)),
        freeze_required=critical_freeze,
        success=success,
    )
    reward_log = build_reward_log(
        run_id=run_id,
        task_id=task_id,
        agent_id=agent_id,
        checks_passed=checks_passed,
        checks_failed=checks_failed,
        strikes=strikes,
        freeze_required=critical_freeze,
    )

    written_outputs = write_non_canonical_outputs(output_dir, audit_event, reward_log)

    response: dict[str, Any] = {
        "run_id": run_id,
        "timestamp": now_iso(),
        "mode": args.mode,
        "branch": branch,
        "task_id": task_id,
        "agent_id": agent_id,
        "staged_files": staged,
        "forbidden_hits": forbidden_hits,
        "violations": unique_errors,
        "required_checks": required_checks,
        "checks_passed": sorted(set(checks_passed)),
        "checks_failed": sorted(set(checks_failed)),
        "authorization_flags": authz_flags,
        "authorization_blockers": prepare_authz_blockers,
        "freeze_required": critical_freeze,
        "audit_event_path": written_outputs[0],
        "reward_log_path": written_outputs[1],
        "check_command_results": check_summaries,
        "strict_schema_summary": strict_schema_result.get("summary", {}),
        "strict_schema_notes": strict_schema_result.get("notes", []),
        "software_verdict": audit_event["software_verdict"],
        "evidence_verdict": audit_event["evidence_verdict"],
        "claim_verdict": NO_CLAIM_ALLOWED,
    }

    if args.mode == "validate-staged":
        render(response, args.pretty)
        return 0 if success else 1

    if prepare_authz_blockers:
        response["prepare_status"] = "BLOCKED_AUTHORIZATION"
        render(response, args.pretty)
        return 1

    if not success:
        response["prepare_status"] = "BLOCKED_VALIDATE_STAGED_FAILED"
        render(response, args.pretty)
        return 1
    if not args.execute_pr_actions:
        response["prepare_status"] = "READY_DRY_RUN_ONLY"
        render(response, args.pretty)
        return 0
    try:
        prepare_commands, pr_url = execute_prepare_actions(args, branch)
    except RuntimeError as exc:
        response["prepare_status"] = "PREPARE_ACTIONS_FAILED"
        response["prepare_error"] = str(exc)
        render(response, args.pretty)
        return 1

    response["prepare_status"] = "DRAFT_PR_CREATED"
    response["draft_pr_url"] = pr_url
    response["prepare_command_results"] = prepare_commands
    render(response, args.pretty)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
