extends Node
# WAVEVALE — UnitData
# Singleton: pool complet des 20 unités jouables.
# Accès global : UnitData.get_unit_template("squire")

const UNIT_POOL: Dictionary = {
	# ── Cost 1 (pool 18) ──────────────────────────────────────────────────────
	"squire": {
		"id": "squire",
		"name": "Squire",
		"emoji": "🛡️",
		"cost": 1,
		"atk": 30,
		"max_hp": 200,
		"range": 1,
		"speed": 1,
		"traits": ["Knight", "Warrior"],
		"star": 1,
		"desc": "Stalwart defender of the realm.",
		"pool_size": 18,
	},
	"archer": {
		"id": "archer",
		"name": "Archer",
		"emoji": "🏹",
		"cost": 1,
		"atk": 40,
		"max_hp": 140,
		"range": 3,
		"speed": 1,
		"traits": ["Ranger"],
		"star": 1,
		"desc": "Swift eyes never miss a mark.",
		"pool_size": 18,
	},
	"imp": {
		"id": "imp",
		"name": "Imp",
		"emoji": "😈",
		"cost": 1,
		"atk": 50,
		"max_hp": 120,
		"range": 1,
		"speed": 1,
		"traits": ["Demon"],
		"star": 1,
		"desc": "Mischievous fiend fuelled by malice.",
		"pool_size": 18,
	},
	"acolyte": {
		"id": "acolyte",
		"name": "Acolyte",
		"emoji": "🕯️",
		"cost": 1,
		"atk": 20,
		"max_hp": 160,
		"range": 1,
		"speed": 1,
		"traits": ["Priest"],
		"star": 1,
		"desc": "Devoted servant channelling holy light.",
		"pool_size": 18,
	},
	"scout": {
		"id": "scout",
		"name": "Scout",
		"emoji": "🗡️",
		"cost": 1,
		"atk": 45,
		"max_hp": 130,
		"range": 2,
		"speed": 1,
		"traits": ["Rogue", "Ranger"],
		"star": 1,
		"desc": "Slips through shadows with deadly precision.",
		"pool_size": 18,
	},
	# ── Cost 2 (pool 15) ──────────────────────────────────────────────────────
	"paladin": {
		"id": "paladin",
		"name": "Paladin",
		"emoji": "⚔️",
		"cost": 2,
		"atk": 50,
		"max_hp": 300,
		"range": 1,
		"speed": 1,
		"traits": ["Knight", "Priest"],
		"star": 1,
		"desc": "Holy warrior clad in righteous steel.",
		"pool_size": 15,
	},
	"wizard": {
		"id": "wizard",
		"name": "Wizard",
		"emoji": "🧙",
		"cost": 2,
		"atk": 75,
		"max_hp": 180,
		"range": 3,
		"speed": 1,
		"traits": ["Mage"],
		"star": 1,
		"desc": "Master of arcane devastation.",
		"pool_size": 15,
	},
	"elf_blade": {
		"id": "elf_blade",
		"name": "Elf Blade",
		"emoji": "🌿",
		"cost": 2,
		"atk": 60,
		"max_hp": 200,
		"range": 1,
		"speed": 1,
		"traits": ["Elf", "Rogue"],
		"star": 1,
		"desc": "Graceful duelist of the ancient forests.",
		"pool_size": 15,
	},
	"ghoul": {
		"id": "ghoul",
		"name": "Ghoul",
		"emoji": "💀",
		"cost": 2,
		"atk": 55,
		"max_hp": 250,
		"range": 1,
		"speed": 1,
		"traits": ["Undead"],
		"star": 1,
		"desc": "Ravenous creature of the grave.",
		"pool_size": 15,
	},
	"berserker": {
		"id": "berserker",
		"name": "Berserker",
		"emoji": "🪓",
		"cost": 2,
		"atk": 90,
		"max_hp": 220,
		"range": 1,
		"speed": 1,
		"traits": ["Warrior", "Demon"],
		"star": 1,
		"desc": "Rage-fuelled engine of destruction.",
		"pool_size": 15,
	},
	# ── Cost 3 (pool 12) ──────────────────────────────────────────────────────
	"champion": {
		"id": "champion",
		"name": "Champion",
		"emoji": "🏆",
		"cost": 3,
		"atk": 80,
		"max_hp": 450,
		"range": 1,
		"speed": 1,
		"traits": ["Knight", "Warrior"],
		"star": 1,
		"desc": "Undefeated veteran of a hundred battles.",
		"pool_size": 12,
	},
	"archmage": {
		"id": "archmage",
		"name": "Archmage",
		"emoji": "🔮",
		"cost": 3,
		"atk": 120,
		"max_hp": 220,
		"range": 3,
		"speed": 1,
		"traits": ["Mage", "Elf"],
		"star": 1,
		"desc": "Centuries of study distilled into pure power.",
		"pool_size": 12,
	},
	"assassin": {
		"id": "assassin",
		"name": "Assassin",
		"emoji": "🥷",
		"cost": 3,
		"atk": 130,
		"max_hp": 180,
		"range": 1,
		"speed": 1,
		"traits": ["Rogue", "Demon"],
		"star": 1,
		"desc": "One strike, one kill — no witnesses.",
		"pool_size": 12,
	},
	"lich": {
		"id": "lich",
		"name": "Lich",
		"emoji": "☠️",
		"cost": 3,
		"atk": 100,
		"max_hp": 280,
		"range": 3,
		"speed": 1,
		"traits": ["Undead", "Mage"],
		"star": 1,
		"desc": "Deathless sorcerer bound to eternal darkness.",
		"pool_size": 12,
	},
	"druid": {
		"id": "druid",
		"name": "Druid",
		"emoji": "🌲",
		"cost": 3,
		"atk": 70,
		"max_hp": 350,
		"range": 2,
		"speed": 1,
		"traits": ["Elf", "Priest"],
		"star": 1,
		"desc": "Nature's guardian, healer of the grove.",
		"pool_size": 12,
	},
	# ── Cost 4 (pool 9) ───────────────────────────────────────────────────────
	"warlord": {
		"id": "warlord",
		"name": "Warlord",
		"emoji": "⚡",
		"cost": 4,
		"atk": 140,
		"max_hp": 600,
		"range": 1,
		"speed": 1,
		"traits": ["Knight", "Warrior", "Demon"],
		"star": 1,
		"desc": "Conqueror of realms, breaker of armies.",
		"pool_size": 9,
	},
	"sorcerer": {
		"id": "sorcerer",
		"name": "Sorcerer",
		"emoji": "🌟",
		"cost": 4,
		"atk": 180,
		"max_hp": 300,
		"range": 3,
		"speed": 1,
		"traits": ["Mage", "Dragon"],
		"star": 1,
		"desc": "Raw arcane power given mortal flesh.",
		"pool_size": 9,
	},
	"shadowblade": {
		"id": "shadowblade",
		"name": "Shadowblade",
		"emoji": "🌑",
		"cost": 4,
		"atk": 170,
		"max_hp": 280,
		"range": 1,
		"speed": 1,
		"traits": ["Rogue", "Undead"],
		"star": 1,
		"desc": "Death walks unseen between the living.",
		"pool_size": 9,
	},
	# ── Cost 5 (pool 6) ───────────────────────────────────────────────────────
	"dragon": {
		"id": "dragon",
		"name": "Dragon",
		"emoji": "🐉",
		"cost": 5,
		"atk": 250,
		"max_hp": 800,
		"range": 1,
		"speed": 1,
		"traits": ["Dragon", "Warrior"],
		"star": 1,
		"desc": "Ancient terror — wings that blot out the sun.",
		"pool_size": 6,
	},
	"seraph": {
		"id": "seraph",
		"name": "Seraph",
		"emoji": "👼",
		"cost": 5,
		"atk": 200,
		"max_hp": 700,
		"range": 2,
		"speed": 1,
		"traits": ["Priest", "Knight", "Elf"],
		"star": 1,
		"desc": "Radiant being of divine judgment.",
		"pool_size": 6,
	},
}


func get_unit_template(id: String) -> Dictionary:
	return UNIT_POOL.get(id, {})


func get_all_ids() -> Array:
	return UNIT_POOL.keys()
