extends RefCounted
class_name GardenData

const ALLOWED_STATUSES: Array[String] = [
	"IMPLEMENTED",
	"TESTED",
	"DOCUMENTED_ONLY",
	"PASSIVE",
	"BLOCKED",
	"BLOCKED / UNKNOWN",
	"NOT_FOUND",
	"UNKNOWN",
]

const ALLOWED_SURFACES: Array[String] = [
	"active_runtime_code",
	"tests",
	"artifacts_runtime_outputs",
	"canonical_docs",
	"roadmap_docs_only",
	"inference",
]

const REPORT_TRUTH_SUMMARY := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/10_ROADMAP/UXPILOTE_STUDIO_GARDEN_TRUTH_RETURN_SUMMARY_V1.md"
const REPORT_TOPLEVEL := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/10_ROADMAP/UXPILOTE_STUDIO_GARDEN_TOPLEVEL_READONLY_INVENTORY_V0.md"
const REPORT_OUTPUTS_RUNTIME := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/10_ROADMAP/UXPILOTE_STUDIO_GARDEN_OUTPUTS_RUNTIME_OUTPUTS_READONLY_AUDIT_V0.md"
const REPORT_SCRIPTS := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/10_ROADMAP/UXPILOTE_STUDIO_GARDEN_SCRIPTS_READONLY_AUDIT_V0.md"
const REPORT_DATASETS := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/10_ROADMAP/UXPILOTE_STUDIO_GARDEN_DATASETS_NAMES_ONLY_AUDIT_V0.md"
const REPORT_MODELS := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/10_ROADMAP/UXPILOTE_STUDIO_GARDEN_MODELS_NAMES_ONLY_AUDIT_V0.md"
const REPORT_LEGACY_TRIAGE := "C:/TACTICAL_CHESS_STUDIO/00_STUDIO_CONTROL/08_MIGRATION/PURELAB_LEGACY_COLLECT_TO_DESKTOP_TRIAGE_REPORT_V0.md"

static func layer_reading_modes() -> Array[Dictionary]:
	return [
		{
			"id": "truth_layer",
			"label": "Calque Vérité",
			"shows": ["zones réellement observées", "outputs", "runtime_outputs", "scripts", "datasets", "models", "secrets verrouillé", "PureLab composant"],
			"purpose": "ce qui existe dans le jardin d'après les audits names-only",
			"color": Color(0.60, 0.98, 0.70, 1.0),
		},
		{
			"id": "sensitive_layer",
			"label": "Calque Sensible",
			"shows": ["secrets", "datasets sensibles", "models", "quarantine", "cyberdefense", "telemetry_sanitized"],
			"purpose": "zones à ne pas ouvrir sans HumanGate",
			"color": Color(1.0, 0.30, 0.34, 1.0),
		},
		{
			"id": "flow_layer",
			"label": "Calque Flux",
			"shows": ["flux entrants", "flux sortants", "perte de signal", "feedback humain", "ancrage réel"],
			"purpose": "comprendre comment l'information circule et se dégrade",
			"color": Color(0.54, 0.96, 1.0, 1.0),
		},
		{
			"id": "build_archive_layer",
			"label": "Calque Build / Archive",
			"shows": ["Zone Build", "Archive Zone", "sorties", "sorties runtime", "zones candidates à mise hors système"],
			"purpose": "séparer test hors système, artefacts et rangement propre",
			"color": Color(0.95, 0.82, 0.42, 1.0),
		},
		{
			"id": "target_architecture_layer",
			"label": "Calque Architecture cible",
			"shows": ["structure future du jardin", "PureLab replacé comme composant", "Mistral / Devstral futur noyau possible", "Tool Zone", "Studio Control"],
			"purpose": "anticiper l'organisation future sans prétendre qu'elle est implémentée",
			"color": Color(0.54, 0.92, 0.76, 1.0),
		},
		{
			"id": "roadmap_layer",
			"label": "Calque Roadmap",
			"shows": ["prochaines tranches d'audit", "zones non inspectées", "inconnus", "décisions HumanGate restantes"],
			"purpose": "voir ce qu'il reste à faire",
			"color": Color(0.95, 0.78, 0.32, 1.0),
		},
		{
			"id": "semantic_pyramid_layer",
			"label": "Salle des pyramides",
			"shows": ["Pyramide Architecture Système", "Pyramide Agentique", "Pyramide Rocky IA joueur d’échecs", "Search décide", "Neural propose", "aucune activation agent", "aucun effet système"],
			"purpose": "lire trois architectures distinctes dans une salle propre sans jardin actif, sans agent actif et sans preuve de promotion",
			"color": Color(0.78, 0.88, 1.0, 1.0),
		},
	]

static func architecture_views() -> Array[Dictionary]:
	return [
		{
			"id": "all_views",
			"layer_id": "",
			"label": "Toutes les architectures",
			"shows": ["tous les calques passifs", "jardin de base", "zones vérité V1", "repères hors système"],
			"purpose": "afficher toutes les architectures locales avec une intensité basse et lisible",
			"color": Color(0.86, 0.92, 0.82, 1.0),
		},
		{
			"id": "current_truth_architecture",
			"layer_id": "truth_layer",
			"label": "Architecture actuelle / vérité",
			"shows": ["C:/TACTICAL_CHESS_STUDIO root garden", "outputs", "runtime_outputs", "scripts", "datasets", "models", "secrets locked", "PureLab component"],
			"purpose": "montrer la vérité observée names-only sans lire de contenu",
			"color": Color(0.60, 0.98, 0.70, 1.0),
		},
		{
			"id": "sensitive_architecture",
			"layer_id": "sensitive_layer",
			"label": "Architecture sensible / verrouillée",
			"shows": ["secrets", "datasets", "models", "quarantine", "cyberdefense", "telemetry_sanitized"],
			"purpose": "montrer les zones sensibles HumanGate-only sans ouverture",
			"color": Color(1.0, 0.30, 0.34, 1.0),
		},
		{
			"id": "flow_architecture",
			"layer_id": "flow_layer",
			"label": "Architecture des flux",
			"shows": ["incoming flows", "outgoing flows", "human feedback signal", "signal loss", "reality grounding"],
			"purpose": "montrer le mouvement du signal et sa dégradation symbolique",
			"color": Color(0.54, 0.96, 1.0, 1.0),
		},
		{
			"id": "build_archive_architecture",
			"layer_id": "build_archive_layer",
			"label": "Architecture Build / Archive",
			"shows": ["Build Zone", "Archive Zone", "outputs", "runtime_outputs", "candidate off-system work"],
			"purpose": "séparer bac à sable, archive, sorties et travail candidat hors système",
			"color": Color(0.95, 0.82, 0.42, 1.0),
		},
		{
			"id": "target_architecture",
			"layer_id": "target_architecture_layer",
			"label": "Architecture cible",
			"shows": ["future garden organization", "PureLab as component", "Mistral / Devstral future possible core", "Tool Zone", "Studio Control"],
			"purpose": "montrer l'organisation cible sans prétendre qu'elle est implémentée",
			"color": Color(0.54, 0.92, 0.76, 1.0),
		},
		{
			"id": "roadmap_architecture",
			"layer_id": "roadmap_layer",
			"label": "Architecture roadmap",
			"shows": ["future audit slices", "unknowns", "HumanGate decisions", "uninspected zones"],
			"purpose": "montrer ce qui reste à décider ou auditer",
			"color": Color(0.95, 0.78, 0.32, 1.0),
		},
		{
			"id": "semantic_pyramid_architecture",
			"layer_id": "semantic_pyramid_layer",
			"label": "Salle des pyramides",
			"shows": ["Pyramide Architecture Système", "Pyramide Agentique", "Pyramide Rocky IA joueur d’échecs", "Studio Control", "Tool Zone", "Build Zone", "Archive Zone", "HumanGate", "Merle", "ChatGPT", "Codex", "Local LLM", "Mistral / Devstral", "Engine", "Search décide", "Neural propose", "Evidence"],
			"purpose": "montrer la separation entre architecture systeme, roles assistant/control et Rocky IA joueur d’échecs sans activation, workflow, preuve, promotion, entrainement ni benchmark",
			"color": Color(0.78, 0.88, 1.0, 1.0),
		},
	]

static func zones() -> Array[Dictionary]:
	var rows: Array[Dictionary] = [
		{
			"id": "studio_greenhouse",
			"label": "C:/TACTICAL_CHESS_STUDIO — racine système",
			"metaphor": "Racine du jardin studio complet",
			"meaning": "racine réelle du jardin/studio",
			"layers": ["Calque vérité"],
			"layer_meaning": "Calque vérité actuelle: racine Jardin Studio observée depuis Truth Return V1. Visuel passif, aucun bouton actif.",
			"surface": "canonical_docs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Feedback humain",
			"description": "Racine documentée du jardin complet: C:/TACTICAL_CHESS_STUDIO. Cette zone montre le studio entier comme substrat de lecture, sans scan, sans mesure, sans connexion runtime et sans nouvelle vérité filesystem.",
			"blocked_actions": ["changement runtime", "activation agent", "promotion sans revue humaine"],
			"position": Vector3(0.0, 0.04, 0.0),
			"scale_or_weight": 2.35,
			"color": Color(0.20, 0.50, 0.33, 1.0),
			"shape": "greenhouse",
			"label_offset": Vector3(-4.45, 0.9, -5.15),
			"label_size": 24,
		},
		{
			"id": "central_tree",
			"label": "PureLab — composant du jardin",
			"metaphor": "Massif organisme récupéré",
			"layers": ["Calque vérité", "Calque héritage"],
			"layer_meaning": "Calque héritage / réintégration: PureLab reste composant du jardin, pas racine. Visuel passif seulement.",
			"surface": "active_runtime_code",
			"status": "PASSIVE",
			"authority": "Composant passif, garde humaine",
			"description": "TacticalChessPureLab est représenté comme un composant/tree/massif dans le jardin C:/TACTICAL_CHESS_STUDIO, pas comme la racine du jardin. Ses contenus ne sont pas inspectés dans ces tâches truth-return.",
			"blocked_actions": ["inspection repo", "mutation runtime", "changement d'autorité"],
			"position": Vector3(0.0, 0.52, 0.0),
			"scale_or_weight": 1.75,
			"color": Color(0.24, 0.64, 0.28, 1.0),
			"shape": "tree",
			"label_offset": Vector3(-0.1, 3.85, 0.35),
			"label_size": 38,
		},
		{
			"id": "architecture_layer",
			"label": "Calque architecture cible",
			"metaphor": "Calque transparent du jardin",
			"layers": ["Calque architecture cible"],
			"layer_meaning": "Calque architecture cible: orientation future sans revendication d'implémentation. Visuel passif, aucun bouton actif.",
			"surface": "canonical_docs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Calque symbolique seulement",
			"description": "Zone de carte symbolique en lecture seule. Le calque architecture cible aide à organiser la structure autour du système vivant sans revendiquer une implémentation.",
			"blocked_actions": ["changement runtime", "contrôle workflow", "changement d'autorité"],
			"position": Vector3(-3.6, 0.28, -5.25),
			"scale_or_weight": 1.05,
			"color": Color(0.44, 0.86, 0.60, 1.0),
			"shape": "layer_marker",
			"label_offset": Vector3(0.0, 0.85, -0.2),
			"label_size": 20,
		},
		{
			"id": "roadmap_layer",
			"label": "Calque roadmap",
			"metaphor": "Calque transparent de croissance future",
			"layers": ["Calque roadmap"],
			"layer_meaning": "Calque roadmap: direction future, audit slices et migration possible sans activation. Visuel passif, aucun bouton actif.",
			"surface": "roadmap_docs_only",
			"status": "DOCUMENTED_ONLY",
			"authority": "Roadmap symbolique seulement",
			"description": "Zone de carte symbolique en lecture seule. Le calque roadmap montre le contexte de croissance future; il ne transforme pas un plan en vérité runtime active.",
			"blocked_actions": ["revendication de promotion", "activation", "persistance de décision"],
			"position": Vector3(2.8, 0.3, -5.72),
			"scale_or_weight": 1.05,
			"color": Color(0.95, 0.70, 0.24, 1.0),
			"shape": "layer_marker",
			"label_offset": Vector3(0.0, 0.85, -0.2),
			"label_size": 20,
		},
		{
			"id": "video_game_garden",
			"label": "Forêt de jeux",
			"metaphor": "Un bosquet, un arbre par jeu",
			"layers": ["Calque héritage", "Calque roadmap"],
			"layer_meaning": "Calque héritage / roadmap: lecture de réintégration PureLab et arbres futurs candidats, sans découverte repo.",
			"surface": "roadmap_docs_only",
			"status": "DOCUMENTED_ONLY",
			"authority": "Carte symbolique candidate seulement",
			"description": "Zone de carte symbolique en lecture seule. La forêt de jeux rend la structure du studio lisible comme un arbre par jeu; TacticalChessPureLab reste l'arbre central récupéré actuel.",
			"blocked_actions": ["découverte repo", "activation projet", "métriques réelles"],
			"position": Vector3(-7.35, 0.2, 0.05),
			"scale_or_weight": 1.1,
			"color": Color(0.28, 0.62, 0.24, 1.0),
			"shape": "forest",
			"label_offset": Vector3(-0.2, 1.0, -1.85),
			"label_size": 22,
		},
		{
			"id": "future_game_tree_a",
			"label": "Futur jeu A",
			"metaphor": "Jeune arbre roadmap/candidat",
			"layers": ["Calque roadmap"],
			"layer_meaning": "Calque roadmap: placeholder futur codé en dur, sans création projet ni activation.",
			"surface": "roadmap_docs_only",
			"status": "DOCUMENTED_ONLY",
			"authority": "Placeholder codé en dur",
			"description": "Zone de carte symbolique en lecture seule. Petit arbre placeholder pour un futur jeu, dimensionné avec des valeurs d'exemple codées en dur et non avec des métriques réelles.",
			"blocked_actions": ["création projet", "scan repo", "revendication métrique"],
			"position": Vector3(-7.35, 0.28, -0.95),
			"scale_or_weight": 0.62,
			"color": Color(0.42, 0.74, 0.28, 1.0),
			"shape": "game_tree",
			"label_offset": Vector3(-0.28, 0.74, -0.18),
			"label_size": 15,
		},
		{
			"id": "future_game_tree_b",
			"label": "Futur jeu B",
			"metaphor": "Jeune arbre roadmap/candidat",
			"layers": ["Calque roadmap"],
			"layer_meaning": "Calque roadmap: placeholder futur codé en dur, sans création projet ni activation.",
			"surface": "roadmap_docs_only",
			"status": "DOCUMENTED_ONLY",
			"authority": "Placeholder codé en dur",
			"description": "Zone de carte symbolique en lecture seule. Second arbre placeholder de la forêt de jeux; c'est un visuel candidat, pas une revendication runtime.",
			"blocked_actions": ["création projet", "scan repo", "revendication métrique"],
			"position": Vector3(-7.35, 0.28, 1.05),
			"scale_or_weight": 0.48,
			"color": Color(0.36, 0.66, 0.34, 1.0),
			"shape": "game_tree",
			"label_offset": Vector3(-0.28, 0.66, 0.18),
			"label_size": 15,
		},
		{
			"id": "docs_seed_beds",
			"label": "Semis docs",
			"metaphor": "Planches de semis",
			"layers": ["Calque vérité", "Calque architecture cible"],
			"layer_meaning": "Calque vérité: documents et routage visibles comme ancrage de lecture; calque architecture cible: organisation future passive.",
			"surface": "canonical_docs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Ancrage des sources",
			"description": "Les documents de politique et de routage sont représentés comme des rangées passives plantées.",
			"blocked_actions": ["promotion de source par existence", "création de fichier non routée"],
			"position": Vector3(-4.9, 0.22, -2.9),
			"scale_or_weight": 1.35,
			"color": Color(0.72, 0.55, 0.28, 1.0),
			"shape": "bed",
			"label_offset": Vector3(-0.15, 1.02, -0.62),
			"label_size": 24,
		},
		{
			"id": "runtime_roots",
			"label": "Racines runtime verrouillées",
			"metaphor": "Racines et tronc verrouillés",
			"layers": ["Calque vérité", "Calque sensible", "Calque architecture cible"],
			"layer_meaning": "Calque sensible / verrouillé: racines visibles mais autorité runtime bloquée; calque architecture cible passif.",
			"surface": "active_runtime_code",
			"status": "PASSIVE",
			"authority": "La vérité runtime reste hors de ce candidat",
			"description": "Les racines sont visibles mais verrouillées; le prototype visuel ne peut pas changer l'autorité runtime.",
			"blocked_actions": ["patch runtime", "contrôle processus", "changement d'autorité"],
			"position": Vector3(3.85, 0.28, -2.75),
			"scale_or_weight": 1.7,
			"color": Color(0.32, 0.21, 0.13, 1.0),
			"shape": "roots",
			"label_offset": Vector3(0.65, 1.0, -0.62),
			"label_size": 24,
		},
		{
			"id": "python_tools",
			"label": "Observation passive",
			"metaphor": "Poste dormant lié au merle",
			"layers": ["Calque vérité", "Calque architecture cible"],
			"layer_meaning": "Calque vérité: poste d'observation dormant; aucun lancement d'outil, aucun scan.",
			"surface": "inference",
			"status": "PASSIVE",
			"authority": "Observation passive seulement",
			"description": "Ancienne ambiguïté Observation Tool: cette zone est un poste dormant de lecture, subordonné au sens du merle. Elle ne remplace pas la Zone Outils et ne lance aucun outil.",
			"blocked_actions": ["exécution outil", "découverte fichier", "appel backend"],
			"position": Vector3(4.95, 0.25, 1.75),
			"scale_or_weight": 1.3,
			"color": Color(0.24, 0.48, 0.68, 1.0),
			"shape": "tools",
			"label_offset": Vector3(0.62, 0.95, 0.45),
			"label_size": 23,
		},
		{
			"id": "tests_immune_plants",
			"label": "Plantes immunitaires tests",
			"metaphor": "Plantes immunitaires",
			"layers": ["Calque vérité"],
			"layer_meaning": "Calque vérité: surface de validation représentée passivement; aucun test repo lancé.",
			"surface": "tests",
			"status": "PASSIVE",
			"authority": "Surface de validation, non touchée",
			"description": "Les plantes protectrices marquent les limites de test sans modifier ni lancer les tests.",
			"blocked_actions": ["édition test", "lancement tests repo"],
			"position": Vector3(-4.9, 0.3, 2.45),
			"scale_or_weight": 1.4,
			"color": Color(0.70, 0.16, 0.18, 1.0),
			"shape": "immune",
			"label_offset": Vector3(-0.12, 1.05, 0.76),
			"label_size": 24,
		},
		{
			"id": "artifacts_compost",
			"label": "Sorties",
			"metaphor": "Zone sorties artefacts",
			"layers": ["Calque vérité"],
			"layer_meaning": "Calque vérité: outputs visible comme zone artefact names-only/docs-only, sans lecture de contenu.",
			"surface": "artifacts_runtime_outputs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Vérité names-only/docs-only",
			"description": "outputs est visible comme zone de sorties et d'hygiène artefact candidate. Vérité names-only/docs-only issue des rapports: contenu non lu, aucune suppression, aucun nettoyage, aucune archive et aucune preuve de comportement runtime.",
			"blocked_actions": ["content read", "cleanup", "archive", "sortie manifeste", "sortie modèle", "sortie dossier run"],
			"position": Vector3(-2.45, 0.24, 4.35),
			"scale_or_weight": 1.3,
			"color": Color(0.44, 0.32, 0.20, 1.0),
			"shape": "compost",
			"label_offset": Vector3(-0.55, 1.02, 0.78),
			"label_size": 24,
		},
		{
			"id": "runtime_outputs_zone",
			"label": "Sorties runtime",
			"metaphor": "Traces runtime bornées",
			"layers": ["Calque vérité"],
			"layer_meaning": "Calque vérité: runtime_outputs visible comme zone artefact names-only/docs-only, sans mesure runtime.",
			"surface": "artifacts_runtime_outputs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Vérité names-only/docs-only",
			"description": "runtime_outputs est visible comme zone de sorties runtime et d'hygiène artefact candidate. Vérité names-only/docs-only: contenu non lu, aucune mesure, aucune validation runtime, aucune suppression et aucun nettoyage effectué.",
			"blocked_actions": ["content read", "cleanup", "archive", "latest.json", "lab/runs", "runtime validation claim"],
			"position": Vector3(0.25, 0.24, 4.95),
			"scale_or_weight": 1.45,
			"color": Color(0.50, 0.38, 0.24, 1.0),
			"shape": "compost",
			"label_offset": Vector3(-0.35, 1.05, 0.72),
			"label_size": 23,
		},
		{
			"id": "scripts_zone",
			"label": "Scripts / Outils",
			"metaphor": "Outils verrouillés",
			"layers": ["Calque vérité", "Calque sensible"],
			"layer_meaning": "Calque sensible / verrouillé: scripts est une zone outil/script observée par noms seulement; exécution BLOCKED.",
			"surface": "artifacts_runtime_outputs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Exécution bloquée",
			"description": "scripts est une zone outil/script observée par noms seulement: one top-level entry observed. contenu non lu, aucun lancement, aucune lecture de contenu et exécution BLOCKED. Cette zone n'est pas un lanceur actif.",
			"blocked_actions": ["content read", "script execution", "launch", "scan", "tool activation"],
			"position": Vector3(5.95, 0.25, 0.25),
			"scale_or_weight": 1.2,
			"color": Color(0.30, 0.48, 0.62, 1.0),
			"shape": "tools",
			"label_offset": Vector3(0.56, 0.95, 0.42),
			"label_size": 22,
		},
		{
			"id": "datasets_zone",
			"label": "Données — sensible / entraînement bloqué",
			"metaphor": "Parcelle sensible training-adjacent",
			"layers": ["Calque sensible"],
			"layer_meaning": "Calque sensible / verrouillé: datasets reste training-adjacent; contenu non lu, génération/reset/training bloqués.",
			"surface": "artifacts_runtime_outputs",
			"status": "DOCUMENTED_ONLY",
			"authority": "HumanGate requis",
			"description": "datasets est une zone sensible/training-adjacent. Noms observés seulement: blocked_future_sensitive, chess, cyberdefense, quarantine, tactical_core, telemetry_sanitized. contenu non lu, no content read, no generation, no reset, no training.",
			"blocked_actions": ["content read", "parse", "validation", "generation", "reset", "training", "promotion"],
			"position": Vector3(-7.1, 0.25, 3.25),
			"scale_or_weight": 1.45,
			"color": Color(0.64, 0.26, 0.22, 1.0),
			"shape": "bramble",
			"label_offset": Vector3(-0.85, 1.0, 0.65),
			"label_size": 19,
		},
		{
			"id": "models_zone",
			"label": "Modèles — chargement bloqué",
			"metaphor": "Zone modèles verrouillée",
			"layers": ["Calque sensible"],
			"layer_meaning": "Calque sensible / verrouillé: models reste model-promotion-adjacent; loading, benchmark et promotion bloqués.",
			"surface": "artifacts_runtime_outputs",
			"status": "DOCUMENTED_ONLY",
			"authority": "HumanGate requis",
			"description": "models est une zone sensible/model-promotion-adjacent. Noms observés seulement: chess, lmstudio, quarantine. contenu non lu, no loading, no benchmark, no promotion, no checkpoint creation.",
			"blocked_actions": ["content read", "loading", "evaluation", "benchmark", "creation", "promotion"],
			"position": Vector3(-7.35, 0.28, 5.65),
			"scale_or_weight": 1.35,
			"color": Color(0.38, 0.30, 0.62, 1.0),
			"shape": "roots",
			"label_offset": Vector3(-0.62, 1.0, 0.62),
			"label_size": 21,
		},
		{
			"id": "secrets_locked_zone",
			"label": "Secrets — accès bloqué",
			"metaphor": "Zone verrouillée inconnue",
			"layers": ["Calque sensible"],
			"layer_meaning": "Calque sensible / verrouillé: secrets reste locked/unknown; aucun nom affiché et aucun accès.",
			"surface": "artifacts_runtime_outputs",
			"status": "BLOCKED",
			"authority": "HumanGate only",
			"description": "secrets reste une zone locked/unknown. Aucun nom de fichier n'est affiché, contenu non lu, not inspected, accès bloqué, HumanGate only.",
			"blocked_actions": ["secrets access", "content read", "scan", "copy", "export", "inspection"],
			"position": Vector3(5.85, 0.25, -5.75),
			"scale_or_weight": 1.35,
			"color": Color(0.42, 0.06, 0.12, 1.0),
			"shape": "bramble",
			"label_offset": Vector3(0.32, 1.0, -0.66),
			"label_size": 22,
		},
		{
			"id": "purelab_legacy_triage_zone",
			"label": "PureLab legacy triage",
			"metaphor": "Table de triage desktop",
			"meaning": "copie de triage manuelle sur Desktop, hors scanner live",
			"layers": ["Calque vérité", "Calque roadmap"],
			"layer_meaning": "Calque vérité / roadmap: dossier de triage Desktop prouvé par rapport collect-to-desktop; aucune copie ou lecture live ici.",
			"surface": "roadmap_docs_only",
			"status": "TESTED",
			"authority": "HumanGate manuel",
			"description": "PureLab legacy triage est représenté comme zone desktop collectée pour manipulation humaine. La carte ne lit pas ce dossier; elle reflète seulement le rapport de collecte.",
			"blocked_actions": ["live scan", "content read", "copy", "move", "delete", "rename", "archive"],
			"position": Vector3(-9.9, 0.24, 1.95),
			"scale_or_weight": 1.08,
			"color": Color(0.52, 0.64, 0.50, 1.0),
			"shape": "archive_zone",
			"label_offset": Vector3(-0.25, 0.92, 0.60),
			"label_size": 19,
		},
		{
			"id": "llm_mycelium",
			"label": "Mycélium inférence",
			"metaphor": "Filaments d'inférence",
			"layers": ["Calque architecture cible"],
			"layer_meaning": "Calque architecture cible: contexte d'inférence suggestif et passif, sans décision ni agent.",
			"surface": "inference",
			"status": "PASSIVE",
			"authority": "Suggestif, jamais final",
			"description": "De fins filaments relient le contexte, mais les décisions finales restent hors de l'inférence.",
			"blocked_actions": ["décision autonome", "activation agent", "autorité runtime"],
			"position": Vector3(2.05, 0.2, 4.45),
			"scale_or_weight": 1.25,
			"color": Color(0.65, 0.70, 0.88, 1.0),
			"shape": "mycelium",
			"label_offset": Vector3(0.55, 0.92, 0.72),
			"label_size": 23,
		},
		{
			"id": "merle_audit_scout",
			"label": "Merle — Auditeur / Hygiène / Vérité",
			"metaphor": "Les yeux passifs du système",
			"layers": ["Calque vérité", "Calque architecture cible"],
			"layer_meaning": "Calque vérité: Merle lit audit/hygiène/vérité comme symbole passif; aucun scan réel, aucun agent.",
			"surface": "inference",
			"status": "PASSIVE",
			"authority": "PASSIVE, déclenchement humain seulement",
			"description": "Le merle est les yeux du système: observation passive, audit, hygiène, vérité, détection de dérive et rapport vers la sphère de feedback humain. Il n'est pas un outil, pas un robot, pas un drone et pas un système d'exécution.",
			"blocked_actions": ["mutation", "exécution", "approbation", "activation agent", "scan repo sans revue humaine", "training", "benchmark"],
			"chain": ["Cartographie", "Hygiène", "Vérité", "Audit fusion", "Détection de dérive", "Sphère de feedback vivant"],
			"position": Vector3(-0.90, 4.25, -1.15),
			"scale_or_weight": 1.05,
			"color": Color(0.025, 0.028, 0.03, 1.0),
			"shape": "merle",
			"label_offset": Vector3(-0.45, 0.82, -0.35),
			"label_size": 22,
		},
		{
			"id": "humangate",
			"label": "Sphère de feedback vivant",
			"metaphor": "Réservoir de retour humain",
			"layers": ["Calque vérité", "Calque roadmap"],
			"layer_meaning": "Calque vérité / roadmap: feedback humain comme ancrage vivant et direction de revue, sans approbation automatique.",
			"surface": "roadmap_docs_only",
			"status": "DOCUMENTED_ONLY",
			"authority": "Feedback humain et autorité finale humaine",
			"description": "Sphère d'eau flottante au-dessus de l'arbre TacticalChessPureLab: source et réservoir du feedback humain. Elle montre charge, retour, irrigation et brume d'observation avec une taille symbolique codée en dur; elle n'exécute, ne mute et n'approuve rien automatiquement.",
			"blocked_actions": ["décision automatique", "workflow d'approbation", "activation agent", "mutation runtime"],
			"position": Vector3(0.75, 5.65, -0.95),
			"scale_or_weight": 1.15,
			"color": Color(0.32, 0.76, 0.96, 1.0),
			"shape": "feedback_sphere",
			"label_offset": Vector3(0.35, 0.85, -0.30),
			"label_size": 28,
		},
		{
			"id": "build_zone",
			"label": "Zone Build — bac à sable",
			"metaphor": "Bac à sable / test hors système",
			"layers": ["Calque roadmap"],
			"layer_meaning": "Calque roadmap: préparation future symbolique hors système; aucun build réel et aucune branche Git.",
			"surface": "artifacts_runtime_outputs",
			"status": "PASSIVE",
			"authority": "Hors du système vivant",
			"description": "Zone de préparation et test d'un patch hors système vivant, comme une branche symbolique ou un bac à sable pour éviter doublons et pollution. Ce n'est pas une vraie branche Git et aucun build réel n'est exécuté.",
			"blocked_actions": ["exécution build", "création branche Git", "contrôle processus", "génération artefact"],
			"position": Vector3(10.15, 0.24, -3.35),
			"scale_or_weight": 1.15,
			"color": Color(0.66, 0.56, 0.34, 1.0),
			"shape": "build_zone",
			"label_offset": Vector3(0.0, 0.9, -0.48),
			"label_size": 21,
		},
		{
			"id": "archive_zone",
			"label": "Zone Archive",
			"metaphor": "Stockage propre hors système",
			"layers": ["Calque roadmap"],
			"layer_meaning": "Calque roadmap: stockage symbolique anti-doublon, sans copie, déplacement ni archive réelle.",
			"surface": "artifacts_runtime_outputs",
			"status": "PASSIVE",
			"authority": "Hors du système vivant",
			"description": "Zone de carte symbolique en lecture seule. L'archive représente un stockage propre hors système pour éviter les doublons et garder le jardin vivant non pollué; aucune action d'archive n'existe.",
			"blocked_actions": ["exécution archive", "déplacement fichier", "scan déduplication"],
			"position": Vector3(10.35, 0.24, -0.15),
			"scale_or_weight": 1.2,
			"color": Color(0.36, 0.58, 0.64, 1.0),
			"shape": "archive_zone",
			"label_offset": Vector3(0.0, 0.92, -0.48),
			"label_size": 21,
		},
		{
			"id": "tool_zone",
			"label": "Zone Outils — Godot / Codex",
			"metaphor": "Logiciels professionnels du jardinier",
			"layers": ["Calque architecture cible", "Calque roadmap"],
			"layer_meaning": "Calque architecture cible / roadmap: outils humains hors système vivant; aucun lancement outil.",
			"surface": "inference",
			"status": "PASSIVE",
			"authority": "Outils tenus par l'humain seulement",
			"description": "Zone de logiciels professionnels utilisés par l'humain/jardinier, comme Godot, Codex et futurs outils. Elle reste hors système vivant et ne lance aucun outil, n'exécute aucune action, ne scanne rien et ne se connecte à rien.",
			"blocked_actions": ["lancement outil", "exécution outil", "appel backend"],
			"position": Vector3(10.15, 0.24, 3.15),
			"scale_or_weight": 1.15,
			"color": Color(0.28, 0.56, 0.78, 1.0),
			"shape": "tool_zone",
			"label_offset": Vector3(0.0, 0.9, 0.48),
			"label_size": 21,
		},
		{
			"id": "blocked_bramble",
			"label": "Sol bloqué",
			"metaphor": "Clôture, ronces, sol contaminé",
			"layers": ["Calque sensible", "Calque roadmap"],
			"layer_meaning": "Calque sensible / roadmap: garde-fous et actions interdites restent clôturés.",
			"surface": "roadmap_docs_only",
			"status": "BLOCKED",
			"authority": "Garde-fous de périmètre",
			"description": "Les opérations interdites sont visualisées comme un sol clôturé au bord du jardin.",
			"blocked_actions": ["backend", "télémétrie", "contrôle système", "sortie dataset ou modèle"],
			"position": Vector3(5.75, 0.25, -4.25),
			"scale_or_weight": 1.65,
			"color": Color(0.46, 0.10, 0.18, 1.0),
			"shape": "bramble",
			"label_offset": Vector3(0.35, 1.0, -0.62),
			"label_size": 23,
		},
		{
			"id": "climate_stress",
			"label": "Stress climatique",
			"metaphor": "Indices de climat et de coût",
			"layers": ["Calque vérité"],
			"layer_meaning": "Calque vérité: contexte coût/énergie symbolique seulement, sans métrique réelle.",
			"surface": "artifacts_runtime_outputs",
			"status": "DOCUMENTED_ONLY",
			"authority": "Observation seulement",
			"description": "La lumière chaude et les marqueurs de stress montrent un contexte de coût/énergie sans mesure réelle.",
			"blocked_actions": ["preuve performance", "revendication promotion"],
			"position": Vector3(-5.75, 0.25, -4.65),
			"scale_or_weight": 1.2,
			"color": Color(0.92, 0.48, 0.20, 1.0),
			"shape": "climate",
			"label_offset": Vector3(-0.42, 0.86, -0.48),
			"label_size": 21,
		},
	]
	for zone in rows:
		var zone_id := String(zone.get("id", ""))
		if _provenance_bindings().has(zone_id):
			zone.merge(_provenance_bindings()[zone_id], true)
		if _signal_context().has(zone_id):
			zone.merge(_signal_context()[zone_id], true)
		_apply_master_scene_readability_overrides(zone)
		zone["layer_ids"] = _layer_ids_for_zone(zone)
	return rows

static func _apply_master_scene_readability_overrides(zone: Dictionary) -> void:
	var zone_id := String(zone.get("id", ""))
	var overrides := {
		"studio_greenhouse": {
			"label": "Studio Root",
			"label_offset": Vector3(-1.70, 0.95, -0.35),
			"label_size": 30,
			"description": "Racine documentee du jardin complet: C:/TACTICAL_CHESS_STUDIO. Cette zone reste une ancre visuelle passive sans scan, sans mesure et sans integration live.",
		},
		"central_tree": {
			"label": "PureLab",
			"label_offset": Vector3(-0.05, 3.65, 0.35),
			"label_size": 30,
		},
		"docs_seed_beds": {
			"label": "Studio Control",
			"position": Vector3(-5.0, 0.22, -2.85),
			"label_size": 22,
		},
		"artifacts_compost": {
			"label": "Sorties",
			"position": Vector3(-3.9, 0.24, 4.2),
			"label_offset": Vector3(-0.35, 1.02, 0.74),
		},
		"runtime_outputs_zone": {
			"label": "Runtime",
			"position": Vector3(-1.2, 0.24, 4.5),
			"label_offset": Vector3(-0.25, 1.02, 0.72),
		},
		"purelab_legacy_triage_zone": {
			"label": "Evidence",
			"position": Vector3(1.6, 0.24, 4.3),
			"label_offset": Vector3(0.0, 0.92, 0.60),
			"label_size": 20,
		},
		"scripts_zone": {
			"label": "Scripts",
			"position": Vector3(5.2, 0.25, 1.25),
			"label_offset": Vector3(0.45, 0.95, 0.45),
		},
		"tool_zone": {
			"label": "Outils",
			"position": Vector3(6.6, 0.24, 3.15),
		},
		"datasets_zone": {
			"label": "Données",
			"position": Vector3(-6.7, 0.25, 2.8),
			"label_offset": Vector3(-0.52, 1.0, 0.62),
			"label_size": 20,
		},
		"models_zone": {
			"label": "Modèles",
			"position": Vector3(-6.7, 0.28, 4.9),
			"label_offset": Vector3(-0.42, 1.0, 0.60),
			"label_size": 20,
		},
		"secrets_locked_zone": {
			"label": "Secrets",
			"position": Vector3(-6.7, 0.25, 6.95),
			"label_offset": Vector3(-0.32, 1.0, 0.66),
			"label_size": 20,
		},
		"llm_mycelium": {
			"label": "Rocky IA",
			"metaphor": "Rocky IA / Engine / Search / Neural",
			"position": Vector3(4.95, 0.2, -2.45),
			"label_offset": Vector3(0.30, 0.92, -0.62),
			"label_size": 22,
		},
		"merle_audit_scout": {
			"label": "Merle",
			"label_offset": Vector3(-0.30, 0.82, -0.25),
		},
		"humangate": {
			"label": "Feedback",
			"position": Vector3(0.75, 5.15, -1.10),
			"label_offset": Vector3(0.18, 0.78, -0.26),
			"label_size": 24,
		},
		"build_zone": {
			"label": "Build",
		},
		"archive_zone": {
			"label": "Archive",
		},
	}
	if overrides.has(zone_id):
		zone.merge(overrides[zone_id], true)

static func _provenance_bindings() -> Dictionary:
	return {
		"studio_greenhouse": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO",
			"evidence_report": REPORT_TRUTH_SUMMARY,
			"evidence_level": "racine système documentée",
			"status": "DOCUMENTED_ONLY",
			"surface": "roadmap_docs_only",
			"blocked_actions": ["live filesystem scan", "runtime mutation", "repo scan", "Git", "backend", "telemetry"],
			"human_gate_question": "HumanGate confirme-t-il que cette racine reste l'ancre visuelle, sans scan live ni intégration filesystem?",
			"provenance_link_label": "racine système",
		},
		"artifacts_compost": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/outputs",
			"evidence_report": REPORT_OUTPUTS_RUNTIME,
			"evidence_level": "preuve names-only",
			"status": "DOCUMENTED_ONLY",
			"surface": "artifacts_runtime_outputs",
			"blocked_actions": ["content read", "cleanup", "archive", "copy", "move", "delete", "runtime claim"],
			"human_gate_question": "Quels outputs peuvent rester preuve passive, et lesquels doivent rester bloqués avant toute lecture de contenu?",
			"provenance_link_label": "preuve names-only",
		},
		"runtime_outputs_zone": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/runtime_outputs",
			"evidence_report": REPORT_OUTPUTS_RUNTIME,
			"evidence_level": "preuve names-only",
			"status": "DOCUMENTED_ONLY",
			"surface": "artifacts_runtime_outputs",
			"blocked_actions": ["content read", "cleanup", "archive", "latest.json", "lab/runs", "runtime validation claim"],
			"human_gate_question": "Quels runtime_outputs peuvent être relus plus tard sans créer de revendication runtime?",
			"provenance_link_label": "preuve names-only",
		},
		"scripts_zone": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/scripts",
			"evidence_report": REPORT_SCRIPTS,
			"evidence_level": "preuve names-only",
			"status": "DOCUMENTED_ONLY",
			"surface": "artifacts_runtime_outputs",
			"warning": "execution blocked",
			"blocked_actions": ["content read", "script execution", "launch", "recursive scan", "tool activation"],
			"human_gate_question": "HumanGate autorise-t-il un jour une revue statique de script, en gardant l'exécution bloquée?",
			"provenance_link_label": "bloqué HumanGate",
		},
		"datasets_zone": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/datasets",
			"evidence_report": REPORT_DATASETS,
			"evidence_level": "preuve names-only",
			"status": "DOCUMENTED_ONLY",
			"surface": "artifacts_runtime_outputs",
			"warning": "content/training/generation blocked",
			"blocked_actions": ["content read", "parse", "validation", "generation", "reset", "training", "promotion"],
			"human_gate_question": "Les datasets restent-ils names-only, ou une future tâche metadata-only est-elle acceptable?",
			"provenance_link_label": "bloqué HumanGate",
		},
		"models_zone": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/models",
			"evidence_report": REPORT_MODELS,
			"evidence_level": "preuve names-only",
			"status": "DOCUMENTED_ONLY",
			"surface": "artifacts_runtime_outputs",
			"warning": "loading/benchmark/promotion blocked",
			"blocked_actions": ["content read", "loading", "evaluation", "benchmark", "creation", "promotion"],
			"human_gate_question": "Les modèles restent-ils names-only avant toute inspection metadata-only ou chargement?",
			"provenance_link_label": "bloqué HumanGate",
		},
		"secrets_locked_zone": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/secrets",
			"evidence_report": "not inspected",
			"evidence_level": "non inspecté",
			"status": "BLOCKED / UNKNOWN",
			"surface": "artifacts_runtime_outputs",
			"blocked_actions": ["secrets access", "content read", "scan", "copy", "export", "inspection"],
			"human_gate_question": "Secrets reste-t-il entièrement non inspecté sauf tâche sécurité HumanGate dédiée?",
			"provenance_link_label": "non inspecté",
		},
		"central_tree": {
			"real_path": "C:/TACTICAL_CHESS_STUDIO/repos/games/TacticalChessPureLab",
			"evidence_report": REPORT_TRUTH_SUMMARY,
			"evidence_level": "component only, contents not inspected",
			"status": "PASSIVE",
			"surface": "active_runtime_code",
			"blocked_actions": ["PureLab repo inspection", "content read", "repo scan", "runtime mutation", "Git"],
			"human_gate_question": "PureLab reste-t-il composant visuel passif sans inspection de contenu repo?",
			"provenance_link_label": "lien système",
		},
		"purelab_legacy_triage_zone": {
			"real_path": "C:/Users/Studio-Dev/Desktop/PURELAB_LEGACY_TRIAGE",
			"evidence_report": REPORT_LEGACY_TRIAGE,
			"evidence_level": "rapport collect-to-desktop triage",
			"status": "TESTED",
			"surface": "roadmap_docs_only",
			"blocked_actions": ["live scan", "content read", "copy", "move", "delete", "rename", "archive"],
			"human_gate_question": "HumanGate veut-il traiter manuellement ce triage Desktop sans que la carte lise le disque?",
			"provenance_link_label": "lien système",
		},
	}

static func _layer_ids_for_zone(zone: Dictionary) -> Array[String]:
	var result: Array[String] = []
	var layers: Array = zone.get("layers", [])
	for layer in layers:
		var text := String(layer).to_lower()
		if text.contains("vérité") or text.contains("vÃ©ritÃ©"):
			result.append("truth_layer")
		if text.contains("sensible"):
			result.append("sensitive_layer")
		if text.contains("architecture"):
			result.append("target_architecture_layer")
		if text.contains("roadmap"):
			result.append("roadmap_layer")
	var zone_id := String(zone.get("id", ""))
	if zone.has("incoming_flow") or zone.has("outgoing_flow"):
		result.append("flow_layer")
	if zone_id in ["artifacts_compost", "runtime_outputs_zone", "build_zone", "archive_zone"]:
		result.append("build_archive_layer")
	if zone_id in ["studio_greenhouse", "central_tree", "tool_zone"]:
		result.append("target_architecture_layer")
	if zone_id in ["datasets_zone", "models_zone", "secrets_locked_zone", "scripts_zone", "blocked_bramble"]:
		result.append("sensitive_layer")
	var unique_result: Array[String] = []
	for layer_id in result:
		if not layer_id in unique_result:
			unique_result.append(layer_id)
	return unique_result

static func _signal_context() -> Dictionary:
	return {
		"studio_greenhouse": {
			"incoming_flow": "flux de feedback humain depuis la sphère de feedback vivant",
			"outgoing_flow": "cadre du jardin vers l'arbre central et les planches routées",
			"feedback_signal_strength": "0.92 symbolic",
			"signal_loss": "0.08 symbolique",
			"data_weight": "poids des données symbolique: 2.35 / taille symbolique",
			"reality_grounding": "ancrage réel élevé: feedback humain proche du cadre du jardin",
			"doctrine_note": "La perte de signal est une métaphore visuelle de perte de message et de contrôle de vérité, pas une télémétrie.",
		},
		"central_tree": {
			"incoming_flow": "pluie de feedback plus contexte mycélium/racines",
			"outgoing_flow": "chemins vivants vers docs, tests, racines, artefacts et forêt de jeux",
			"feedback_signal_strength": "0.86 symbolic",
			"signal_loss": "0.14 symbolique",
			"data_weight": "poids des données symbolique: 1.75 / taille symbolique",
			"reality_grounding": "ancrage réel par retour visible vers la sphère d'eau",
			"doctrine_note": "Le feedback humain garde l'arbre central près de la vérité et limite la dérive.",
		},
		"docs_seed_beds": {
			"incoming_flow": "pluie de feedback et trace d'observation passive",
			"outgoing_flow": "contexte de source ancrée vers le jardin",
			"feedback_signal_strength": "0.74 symbolic",
			"signal_loss": "0.26 symbolique",
			"data_weight": "poids des données symbolique: 1.35 / taille symbolique",
			"reality_grounding": "ancrage réel par ancrage des sources et revue humaine",
			"doctrine_note": "Plus de relais implique plus de perte de signal possible; les docs réduisent la dérive.",
		},
		"tests_immune_plants": {
			"incoming_flow": "pluie de feedback humain atténuée",
			"outgoing_flow": "signal de frontière validation vers le système vivant",
			"feedback_signal_strength": "0.68 symbolic",
			"signal_loss": "0.32 symbolique",
			"data_weight": "poids des données symbolique: 1.40 / taille symbolique",
			"reality_grounding": "ancrage réel par validation bornée seulement",
			"doctrine_note": "Les tests sont des plantes de contrôle de vérité, pas un vrai lancement de tests ici.",
		},
		"artifacts_compost": {
			"incoming_flow": "eau de feedback atténuée vers le sol candidat",
			"outgoing_flow": "preuve par relecture et retour feedback",
			"feedback_signal_strength": "0.58 symbolic",
			"signal_loss": "0.42 symbolique",
			"data_weight": "poids des données symbolique: 1.60 / taille symbolique",
			"reality_grounding": "ancrage réel seulement quand l'humain relit les preuves",
			"doctrine_note": "Les artefacts candidats ont besoin de feedback humain pour éviter les fausses revendications de prêt.",
		},
		"runtime_outputs_zone": {
			"incoming_flow": "trace names-only depuis les rapports truth-return",
			"outgoing_flow": "retour d'hygiène artefact vers HumanGate",
			"feedback_signal_strength": "0.46 symbolic",
			"signal_loss": "0.54 symbolique",
			"data_weight": "poids des données symbolique: runtime_outputs names-only",
			"reality_grounding": "ancrage limité: contenu non lu, aucune mesure runtime",
			"doctrine_note": "Sorties runtime est une zone de lecture candidate, pas une preuve de comportement runtime.",
		},
		"scripts_zone": {
			"incoming_flow": "signal de risque outil/script depuis la vérité names-only",
			"outgoing_flow": "alerte d'exécution bloquée vers la sphère de feedback vivant",
			"feedback_signal_strength": "0.34 symbolic",
			"signal_loss": "0.66 symbolique",
			"data_weight": "poids des données symbolique: one top-level entry observed",
			"reality_grounding": "ancrage names-only: contenu non lu, exécution BLOCKED",
			"doctrine_note": "Scripts / Outils ne lance rien; c'est un marqueur de frontière, pas une interface d'action.",
		},
		"datasets_zone": {
			"incoming_flow": "signal sensible depuis datasets names-only",
			"outgoing_flow": "barrière HumanGate contre génération, reset et entraînement",
			"feedback_signal_strength": "0.28 symbolic",
			"signal_loss": "0.72 symbolique",
			"data_weight": "poids des données symbolique: 6 noms top-level",
			"reality_grounding": "ancrage faible volontaire: contenu non lu, entraînement bloqué",
			"doctrine_note": "Les noms affichés dans l'inspecteur ne sont pas un droit de lecture, de validation, de génération ou de training.",
		},
		"models_zone": {
			"incoming_flow": "signal sensible depuis models names-only",
			"outgoing_flow": "barrière HumanGate contre chargement, benchmark et promotion",
			"feedback_signal_strength": "0.30 symbolic",
			"signal_loss": "0.70 symbolique",
			"data_weight": "poids des données symbolique: 3 noms top-level",
			"reality_grounding": "ancrage faible volontaire: contenu non lu, chargement bloqué",
			"doctrine_note": "Les modèles restent une zone verrouillée; aucune évaluation, benchmark, création ou promotion n'est impliquée.",
		},
		"secrets_locked_zone": {
			"incoming_flow": "alerte de zone inconnue et verrouillée",
			"outgoing_flow": "arrêt net vers HumanGate only",
			"feedback_signal_strength": "0.12 symbolic",
			"signal_loss": "0.88 symbolique",
			"data_weight": "poids des données symbolique: inconnu, non inspecté",
			"reality_grounding": "ancrage par blocage explicite: accès bloqué, aucun nom affiché",
			"doctrine_note": "Secrets n'est pas inspecté; la carte montre seulement le verrou et l'autorité HumanGate.",
		},
		"llm_mycelium": {
			"incoming_flow": "contexte depuis l'arbre central et retour feedback",
			"outgoing_flow": "filaments d'inférence suggestive vers la sphère d'eau",
			"feedback_signal_strength": "0.52 symbolic",
			"signal_loss": "0.48 symbolique",
			"data_weight": "poids des données symbolique: 1.25 / taille symbolique",
			"reality_grounding": "ancrage réel moyen: l'inférence reste suggestive et jamais finale",
			"doctrine_note": "Une inférence coupée du feedback humain risque la dérive; la sphère l'ancre.",
		},
		"runtime_roots": {
			"incoming_flow": "chemin racine depuis l'arbre central plus retour feedback",
			"outgoing_flow": "signal de stabilité des racines verrouillées vers la frontière architecture",
			"feedback_signal_strength": "0.62 symbolic",
			"signal_loss": "0.38 symbolique",
			"data_weight": "poids des données symbolique: 1.70 / taille symbolique",
			"reality_grounding": "la vérité runtime reste verrouillée hors de ce candidat visuel",
			"doctrine_note": "La carte explique les racines mais ne peut pas muter l'autorité runtime.",
		},
		"python_tools": {
			"incoming_flow": "brume d'observation passive et flux lié sélectionné",
			"outgoing_flow": "retour d'observation passive vers la sphère de feedback vivant",
			"feedback_signal_strength": "0.50 symbolic",
			"signal_loss": "0.50 symbolique",
			"data_weight": "poids des données symbolique: 1.30 / taille symbolique",
			"reality_grounding": "ancrage réel passif: poste dormant, pas une zone outils",
			"doctrine_note": "Aucun lancement d'outil n'existe; le feedback marque seulement le retour d'observation.",
		},
		"merle_audit_scout": {
			"incoming_flow": "trace d'observation passive depuis docs et sol bloqué",
			"outgoing_flow": "rapport vers la sphère de feedback vivant",
			"feedback_signal_strength": "0.70 symbolic",
			"signal_loss": "0.30 symbolique",
			"data_weight": "poids des données symbolique: 1.05 / taille symbolique",
			"reality_grounding": "ancrage réel par lecture humaine du rapport",
			"doctrine_note": "Merle est auditeur/hygiène/vérité en observation passive, pas un agent actif.",
		},
		"humangate": {
			"incoming_flow": "retour feedback et brume d'observation",
			"outgoing_flow": "flux de feedback humain, pluie de feedback et irrigation de la sphère",
			"feedback_signal_strength": "1.00 symbolic",
			"signal_loss": "0.00 symbolique à la source",
			"data_weight": "poids des données symbolique: 1.15 / taille symbolique",
			"reality_grounding": "source et réservoir du feedback humain, ancrage réel final",
			"doctrine_note": "La sphère de feedback vivant est la source d'ancrage réel; les valeurs sont symboliques seulement.",
		},
		"build_zone": {
			"incoming_flow": "intention de patch depuis le feedback humain, hors système vivant",
			"outgoing_flow": "retour de lecture vers revue humaine avant toute promotion",
			"feedback_signal_strength": "0.40 symbolique",
			"signal_loss": "0.60 symbolique",
			"data_weight": "poids des données symbolique: 1.15 / taille symbolique",
			"reality_grounding": "ancrage réel par bac à sable et test hors système",
			"doctrine_note": "Zone Build signifie branche symbolique de préparation; ce n'est pas une vraie branche Git et aucun build réel n'est exécuté.",
		},
		"archive_zone": {
			"incoming_flow": "signal anti-doublon depuis le jardin",
			"outgoing_flow": "rappel de stockage propre vers feedback humain",
			"feedback_signal_strength": "0.38 symbolique",
			"signal_loss": "0.62 symbolique",
			"data_weight": "poids des données symbolique: 1.20 / taille symbolique",
			"reality_grounding": "ancrage réel par séparation hors système",
			"doctrine_note": "Archive est un symbole de rangement; aucune archive réelle, aucun déplacement, aucun scan.",
		},
		"tool_zone": {
			"incoming_flow": "besoin humain de logiciels professionnels",
			"outgoing_flow": "orientation passive vers Godot, Codex et futurs outils",
			"feedback_signal_strength": "0.44 symbolique",
			"signal_loss": "0.56 symbolique",
			"data_weight": "poids des données symbolique: 1.15 / taille symbolique",
			"reality_grounding": "ancrage réel par outils tenus par l'humain, hors système vivant",
			"doctrine_note": "Zone Outils représente Godot, Codex et futurs logiciels; elle ne lance aucun outil et n'exécute aucune action.",
		},
		"blocked_bramble": {
			"incoming_flow": "eau d'alerte atténuée depuis la sphère de feedback vivant",
			"outgoing_flow": "alerte de périmètre bloqué vers Merle et feedback humain",
			"feedback_signal_strength": "0.36 symbolic",
			"signal_loss": "0.64 symbolique",
			"data_weight": "poids des données symbolique: 1.65 / taille symbolique",
			"reality_grounding": "ancrage réel par actions bloquées explicites, pas par mesure",
			"doctrine_note": "La forte perte de signal marque une frontière où les revendications d'action doivent s'arrêter.",
		},
	}
